### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by Yama-K** [Czechball/discord-video#4]
Started to compress a video sized at 16.9mb, ended with 53.7mb file. This was on the windows .bat file.

**Comment by Czechball** [comment]
Hey. That's pretty weird. Would you mind sharing the ffprobe output of the video or even the video itself?

**Comment by Yama-K** [comment]
Sorry for slow reply, I don't seem to find the log files anywhere, I suspect it could have something to do with the video going from mp4 to webm, although it seems too drastic of a change on the filesize especially since the .bat automatically lowers the resolution. 

The video file is from nvidia shadowplay trimmed with Microsoft Photos and then compressed with the .bat, I see no reason to share the video itself, perhaps this was just one time thing, haven't tested the script again after that though.

**Comment by a8underscore** [comment]
started with 30GB source, ended up at 14.2MB
https://paste.gg/p/anonymous/b9d449516d4d4a90b9e147c105298159
