### ISSUE TITLE
Should %VIDEO_BITRATE% be in a bash script?

### ISSUE THREAD

**Issue by ZacharyTalis** [Czechball/discord-video#6]
Neato script!

[This line](https://github.com/Czechball/discord-video/blob/179ca5cfcd0bd6420d37c42e7d4ca7afd5bcae26/discord-video.sh#L33) uses `%VIDEO_BITRATE%` (towards the end). Should it be `$VIDEO_BITRATE`?

Script failed on my Linux machine until tweaking this. Error message:

```bash
[libvpx-vp9 @ 0x55961f169840] [Eval @ 0x7fff73449e70] Undefined constant or missing '(' in '%VIDEO_BITRATE%'
[libvpx-vp9 @ 0x55961f169840] Unable to parse option value "%VIDEO_BITRATE%"
[libvpx-vp9 @ 0x55961f169840] Error setting option b to value %VIDEO_BITRATE%.
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
```

**Comment by Czechball** [comment]
Seems like @RealOfficialTurf broke it here: https://github.com/Czechball/discord-video/commit/fcfe83e90d5bfc5df99db2a9172690bfc29da074
Will fix..

**Comment by Czechball** [comment]
https://github.com/Czechball/discord-video/commit/3d4010bc6d1aac853837ab322f044377e664947c
